apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpdapp
  template:
    metadata:
      labels:
        app: httpdapp
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
