apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32762
  type: NodePort