apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shradha-pod-reader-binding
  namespace: default
subjects:
- kind: User
  name: "shradha"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io