apiVersion: v1
kind: Service
metadata:
  name: project-frontend
spec:
  type: NodePort
  selector:
    app: project-frontend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32762