apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO: bW9uZ29kYitzcnY6Ly9zaHJhZGhhOnNocmFkaGFAY2x1c3RlcjAuZDdsbTEubW9uZ29kYi5uZXQv
# base64 encoding of mongodb+srv://shradha:shradha@cluster0.d7lm1.mongodb.net/