apiVersion: v1
kind: Pod
metadata:
  name: ssd-preferred-pod
spec:
  containers:
    - name: app
      image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: disk
                operator: In
                values:
                  - ssd