apiVersion: v1
kind: Pod
metadata:
  name: critical-pod
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "critical"
      effect: "NoSchedule"