apiVersion: v1
kind: Pod
metadata:
  name: web-secret
spec:
  containers:
    - name: web-container
      image: nginx
      env:
        - name: APP_ENV
          value: "production"
        - name: DATABASE_URL
          value: "mysql://db.example.com:3306/prod_db"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_PASSWORD