apiVersion: v1
kind: Pod
metadata:
  name: api
spec:
  containers:
    - name: api-container
      image: nginx
      env:
        - name: APP_ENV
          value: "production"
        - name: DATABASE_URL
          value: "mysql://db.example.com:3306/prod_db"